namespace Oraculo.Models
{
    public class R2QPurchaseInvoices
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Proveedor { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string HoraCadena { get; set; }
        public string Sucursal { get; set; }
        public string Estacion { get; set; }
        public string Usuario { get; set; }
        public string Tipo { get; set; }
        public string Status { get; set; }
        public string DocDestino { get; set; }
        public string Referencia { get; set; }
        public string CondCredito { get; set; }
        public int? DiasCredito { get; set; }
        public string FechaEntrega { get; set; }
        public decimal? DescAcumulable1 { get; set; }
        public decimal? DescAcumulable2 { get; set; }
        public string ConceptoGastos { get; set; }
        public decimal? ImporteGastos { get; set; }
        public string Comentario { get; set; }
        public string Moneda { get; set; }
        public decimal? TipoCambio { get; set; }
        public decimal? DctoPorcentaje { get; set; }
        public decimal? DctoMonto { get; set; }
        public decimal? TotalNeto { get; set; }
        public decimal? TotalNetoMoned { get; set; }
        public decimal? ImporteNetoGastos { get; set; }
        public string IndicadorImpuestos { get; set; }
        public decimal? TasaImpuesto { get; set; }
        public string Autorizado { get; set; }
        public string Sincronizado { get; set; }
        public string FolioCortex { get; set; }
        public string Prefijo { get; set; }
        public string Folio { get; set; }
        public string FechaContabili { get; set; }
        public string FechaDocumento { get; set; }
        public string FechaVencimiento { get; set; }
        public string ArchivoPdf { get; set; }
        public string ArchivoXml { get; set; }
        public decimal? TotalFisico { get; set; }
        public string FolioUuid { get; set; }
        public string Repartido { get; set; }
        public string VersionR1 { get; set; }
        public string FechaCancelOc { get; set; }
        public string ProveedorSec { get; set; }
        public string FolioRefOc { get; set; }
        public string RecepcionParcial { get; set; }
        public string FolioFaInter { get; set; }
        public string SucFilProve { get; set; }
        public string CompRocCentral { get; set; }
        public string VersComproCent { get; set; }
        public string RedondeoMoneda { get; set; }
        public string Parametro01 { get; set; }
        public string Parametro02 { get; set; }
        public string ComponenOrigen { get; set; }
        public string DetalleCode { get; set; }
        public string DetalleName { get; set; }
        public string DetalleFolio { get; set; }
        public int? NumPartida { get; set; }
        public string NumeroArticulo { get; set; }
        public decimal? Cantidad { get; set; }
        public decimal? CantidadAb { get; set; }
        public decimal? Pbsd { get; set; }
        public decimal? Pbcd { get; set; }
        public decimal? Pnsd { get; set; }
        public decimal? Pncd { get; set; }
        public decimal? Descuento { get; set; }
        public decimal? Impuesto { get; set; }
        public decimal? ImporteNeto { get; set; }
        public string DetalleMoneda { get; set; }
        public decimal? DetalleTipoCambio { get; set; }
        public string ListaMat { get; set; }
        public string EsPadre { get; set; }
        public string TipoLm { get; set; }
        public decimal? CantidadOrig { get; set; }
        public string CodigoAlt { get; set; }
        public string DocumentoBase { get; set; }
        public string PartidaBase { get; set; }
        public string Comentarios { get; set; }
        public string Almacen { get; set; }
        public string DetalleIndicaImpuesto { get; set; }
        public decimal? DetalleTasaImpuesto { get; set; }
        public decimal? CantidadSc { get; set; }
        public string ListaPrecios { get; set; }
        public string? PrecioManual { get; set; }
        public string MedidaInventa { get; set; }
        public string UnidadCompra { get; set; }
        public string PartidaSbo { get; set; }
        public decimal? CantidadEmpaq { get; set; }
        public string CodigoEmpaq { get; set; }
        public string CodigoDesempaq { get; set; }
        public string UnidadMedidaIn { get; set; }
        public string CodiUniMedInv { get; set; }
        public decimal? CantUniMedInv { get; set; }
        public string Descripcion { get; set; }
        public decimal? CantExistencia { get; set; }
        public decimal? CantPropuesta { get; set; }
        public decimal? Retencion { get; set; }
        public string CodigoSAT { get; set; }
        public decimal? Ieps { get; set; }
        public string CodArt { get; set; }
        public string NomProv { get; set; }
        public string RFC { get; set; }
    }
}
